import type { AppLocale } from './privacyCopy';

export const GROWTH_COPY = {
  en: {
    marketingLabel:
      'Also send me occasional Mapshroom product updates and tips (optional). You can unsubscribe anytime.',
    marketingTitle: 'Stay in the loop',
    marketingTitleCompact: 'Get product updates',
    marketingLabelCompact: 'Optional tips and release notes — unsubscribe anytime.',
    privacyNoteBefore: 'By continuing you agree to the ',
    privacyLink: 'Privacy Policy',
    privacyNoteMiddle: ' and ',
    betaLink: 'Desktop beta terms',
    privacyNoteAfter: '.',
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.com',
    submitDownload: 'Email me the Windows beta download',
    submitDownloadCompact: 'Send download link',
    submitNewsletter: 'Subscribe to newsletter',
    submitProfile: 'Create passwordless profile',
    submitProBeta: 'Join Pro waitlist',
    sending: 'Sending…',
    successTitle: 'Check your email',
    successBody:
      'If this address can receive mail, we sent a verification link. Open it, confirm, then download.',
    successBodyCompact: 'Open the link we sent, confirm, then download the installer.',
    resend: 'Resend link',
    desktopBetaTitle: 'Windows desktop beta',
    desktopBetaLead:
      'Offline Mapshroom for Windows is in free beta. Leave your email to receive a download link. Marketing updates are optional and separate.',
    desktopEmailPrompt: 'Enter your email to get the Windows beta download link.',
    downloadCtaShort: 'Windows beta',
    preferWebInstall: 'Prefer the free web app?',
    hideWebInstall: 'Hide web app option',
    onlineTitle: 'Online / install as web app',
    onlineLead:
      'The web version stays free and does not require email. Install it to your dock or home screen.',
    verifyReadyTitle: 'Confirm your email',
    verifyReadyBody: 'Press the button below to verify this address and unlock your download.',
    verifyConfirm: 'Verify email and continue',
    verifyInvalid: 'This verification link is invalid.',
    verifyExpired: 'This verification link expired. Request a new one from the download page.',
    verifyConsumed: 'This link was already used. If you are signed in, you can download again.',
    verifySuccess: 'Email verified. Your download is ready.',
    downloadCta: 'Download Windows installer',
    profileTitle: 'Your Mapshroom profile',
    profileLead:
      'Passwordless email profile. Creative projects still stay on your device unless you export them.',
    feedbackTitle: 'Send feedback',
    feedbackLead: 'Tell us what worked, what broke, or what you want next.',
    feedbackSubmit: 'Send feedback',
    feedbackThanks: 'Thanks — your feedback is in.',
    categoryBug: 'Bug',
    categoryFeature: 'Feature idea',
    categoryPraise: 'Praise',
    categoryOther: 'Other',
    ratingLabel: 'Usefulness (1–5)',
    messageLabel: 'Message',
    optionalEmailLabel: 'Email (optional)',
  },
  it: {
    marketingLabel:
      'Voglio anche ricevere aggiornamenti e consigli occasionali su Mapshroom (opzionale). Posso annullare in qualsiasi momento.',
    marketingTitle: 'Resta aggiornato',
    marketingTitleCompact: 'Ricevi aggiornamenti',
    marketingLabelCompact: 'Opzionale: novità e consigli — annulla quando vuoi.',
    privacyNoteBefore: 'Continuando accetti la ',
    privacyLink: 'Privacy Policy',
    privacyNoteMiddle: ' e i ',
    betaLink: 'termini della beta desktop',
    privacyNoteAfter: '.',
    emailLabel: 'Email',
    emailPlaceholder: 'tu@example.com',
    submitDownload: 'Inviami il download della beta Windows',
    submitDownloadCompact: 'Invia link di download',
    submitNewsletter: 'Iscriviti alla newsletter',
    submitProfile: 'Crea profilo senza password',
    submitProBeta: 'Entra in lista d’attesa Pro',
    sending: 'Invio…',
    successTitle: 'Controlla la posta',
    successBody:
      'Se questo indirizzo può ricevere email, abbiamo inviato un link di verifica. Aprilo, conferma e poi scarica.',
    successBodyCompact: 'Apri il link inviato, conferma e scarica l’installer.',
    resend: 'Reinvia link',
    desktopBetaTitle: 'Beta desktop Windows',
    desktopBetaLead:
      'Mapshroom offline per Windows è in beta gratuita. Lascia la tua email per ricevere il link di download. Gli aggiornamenti marketing sono opzionali e separati.',
    desktopEmailPrompt: 'Inserisci la tua email per ricevere il link della beta Windows.',
    downloadCtaShort: 'Beta Windows',
    preferWebInstall: 'Preferisci la web app gratuita?',
    hideWebInstall: 'Nascondi opzione web app',
    onlineTitle: 'Online / installa come web app',
    onlineLead:
      'La versione web resta gratuita e non richiede email. Installala sul dock o nella home.',
    verifyReadyTitle: 'Conferma la tua email',
    verifyReadyBody: 'Premi il pulsante qui sotto per verificare questo indirizzo e sbloccare il download.',
    verifyConfirm: 'Verifica email e continua',
    verifyInvalid: 'Questo link di verifica non è valido.',
    verifyExpired: 'Questo link è scaduto. Richiedine uno nuovo dalla pagina download.',
    verifyConsumed: 'Questo link è già stato usato. Se sei connesso, puoi scaricare di nuovo.',
    verifySuccess: 'Email verificata. Il download è pronto.',
    downloadCta: 'Scarica installer Windows',
    profileTitle: 'Il tuo profilo Mapshroom',
    profileLead:
      'Profilo email senza password. I progetti creativi restano sul dispositivo, salvo export.',
    feedbackTitle: 'Invia feedback',
    feedbackLead: 'Dicci cosa ha funzionato, cosa no, o cosa vorresti dopo.',
    feedbackSubmit: 'Invia feedback',
    feedbackThanks: 'Grazie — feedback ricevuto.',
    categoryBug: 'Bug',
    categoryFeature: 'Idea funzione',
    categoryPraise: 'Complimento',
    categoryOther: 'Altro',
    ratingLabel: 'Utilità (1–5)',
    messageLabel: 'Messaggio',
    optionalEmailLabel: 'Email (opzionale)',
  },
} as const;

export function growthCopy(locale: AppLocale) {
  return GROWTH_COPY[locale];
}
